type Query {
    findAllBooks: [Book!]!
    findBookById(id: Int): Book,
    findBooksByPublishedDate(publishedDate: String): [Book!]!
}

# We will be having a list of mutations actions that will be updating data in our database.
# All elements are required strings.
type Mutation {
    createBook(title: String!, authorName: String!, publishedDate: String!): Book,
    updateBook(id: Int!, title: String!, authorName: String!, publishedDate: String!): Book,
    deleteBook(id: Int!) : Book
}

type Book {
    id: Int
    title: String
    author: Author       # Changing to be an Author object
    publishedDate: String
}

# Creating the Author type
type Author {
    id: Int
    name: String
}