import { Book } from '../features/bookReducer';

const GRAPHQL_URL = 'http://localhost:8080/graphql';

/**
 * This will be responsible for fetching all the book from the backend
 * and at the end returns an array of books or empty if there isn't any book in the database.
 * @returns List of books or empty array
 */
export const fetchBooks = async (): Promise<Book[]> => {
    const response = await fetch(GRAPHQL_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            query: `{
        findAllBooks {
          id
          title
          author
          publishedDate
        }
      }`,
        }),
    });

    // checking if we have a valid response from the backend
    if (!response.ok) {
        throw new Error(`Failed to fetch books: ${response.status} ${response.statusText}`);
    }

    // loading and checking if the data is a valid json
    const { data } = await response.json();
    if (!data || !data.findAllBooks) {
        throw new Error("Invalid JSON data format");
    }

    return data.findAllBooks;
};

export const fetchBookById = async (id: number): Promise<Book> => {
    const response = await fetch(GRAPHQL_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            query: `{
        findBookById {
          id
          title
          author
          publishedDate
        }
      }`,
            variables: { id: id },
        }),
    });

    // checking if we have a valid response from the backend
    if (!response.ok) {
        throw new Error(`Failed to fetch book: ${response.status} ${response.statusText}`);
    }

    // loading and checking if the data is a valid json
    const { data } = await response.json();

    // checking if we have errors in the response
    if (data.errors && data.errors.length > 0) {
        throw new Error(data.errors[0].message);
    }

    return data.findBookById;
};

/**
 * This will be responsible for creating a new book in the backend
 * it will be receiving a book object without ID and it will be returning
 * the created book with ID generated by the backend.
 * @param book Book object without ID
 * @returns Created book with ID
 */
export const createBook = async (book: Omit<Book, 'id'>): Promise<Book> => {
    const response = await fetch(GRAPHQL_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            query: `mutation($title: String!, $author: String!, $publishedDate: String!) {
        createBook(title: $title, author: $author, publishedDate: $publishedDate) {
          id
          title
          author
          publishedDate
        }
      }`,
            variables: book,
        }),
    });

    // checkinf if we have a valid response from the backend
    if (!response.ok) {
        throw new Error(`Failed to create book: ${response.status} ${response.statusText}`);
    }

    // so we can get the json data and check if we have errors in the response
    const { data } = await response.json();
    if (data.errors && data.errors.length > 0) {
        throw new Error(data.errors[0].message);
    }

    return data.createBook;
};

/**
 * This will be responsible for deleting a book in the backend by its ID
 * @param id book ID to delete
 * @returns the deleted book object, or null if the book was not found.
 */
export const deleteBook = async (id: number): Promise<number> => {
    const response = await fetch(GRAPHQL_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            query: `mutation($id: Int!) {
        deleteBook(id: $id) {
          id
        }
      }`,
            variables: { id: id },
        }),
    });

    const { data } = await response.json();
    return data.deleteBook;
};
